### ISSUE TITLE
React dependency

### ISSUE THREAD

**Issue by anaibol** [developit/preact-compat-example#1]
Hi, I was trying to use preact with redux and react-redux. Apparently there is no more proptypes on preact. I was asking me, why do you need React as a dependency if you have preact-compat. In which case wouldn you use react, preact, and preact-compat?

Thanks and amazing project!

**Comment by developit** [comment]
Hi Juan,

I'm actually not sure why `react` is still in the `package.json`, but if you're talking about in the source code, any `"react"` or `"react-dom"` imports actually get shimmed so they return [`preact-compat`](http://git.io/preact-compat).  

Regarding PropTypes, `preact` itself does not provide them, they are a standalone library called [`proptypes`](http://git.io/proptypes).  When you import `react` (which really imports `preact-compat`), that library is exposed as `PropTypes`:

``` js
import React, { Component } from 'react';
import { render } from 'react-dom';

class Foo extends Component {
    static propTypes = {
        foo: React.PropTypes.string,
    }

    render() {
        let { bar, children } = this.props;
        return <div foo={ bar }>{ children }</div>;
    }
}

render(<Foo bar="baz">test</Foo>, document.body);
```

^ because React gets replaced during builds, the above is functionally identical to this preact-flavored implementation:

``` js
import { h, render, Component } from 'preact';
import PropTypes from 'proptypes';

class Foo extends Component {
    static propTypes = {
        foo: PropTypes.string,
    }

    render({ bar, children }) {
        return <div foo={ bar }>{ children }</div>;
    }
}

render(<Foo bar="baz">test</Foo>, document.body);
```

Let me know if this answers your question :)

**Comment by anaibol** [comment]
Thanks for the help!
I replaced some 'react' for 'preact' on the react-redux dependency. I thought that maybe preact-compat does not make the compatibility in the node_modules folder. I also replaced the parts using React.PropTypes for PropTypes.
I have now this error. It seems that it's not replacing that 'React.createElement'. I am right?
Thanks again! Redux is a modern pattern based on Flux and is today on the top of the trend, I think that using preact as a replacement for react + redux would be awesome!

![error](https://cloud.githubusercontent.com/assets/3210177/11532799/9a687a24-9906-11e5-9634-824f5285d563.png)

**Comment by developit** [comment]
@anaibol Instead of replacing `react` with `preact`, replace it with `preact-compat`.  That will give you `.createElement()` and `.PropTypes`.  You can also have WebPack [do it for you automatically](https://github.com/developit/preact-compat-example/blob/master/webpack.config.babel.js#L15-L18).

Regrading Redux, I completely agree.  I'll be releasing both `preact-redux` and an example project using it shortly, stay tuned :)

Also if you run into anything and need help, feel free to drop into the [Preact Gitter Room](https://gitter.im/developit/preact).

**Comment by anaibol** [comment]
In fact I am already using the Webpack way but it's not working in all cases. I am not sure if it's the Webpack transformation or the way that react-redux works. That 'React.createElement' is after the preact-compat Webpack transformation.

**Comment by developit** [comment]
Are you defining a custom JSX Pragma somewhere?  Inside my code I use `h()` (`/**@jsx h*/`), but within libraries, since they are pre-transpiled they still use `React.createElement()`.

To fix the issue you took that screenshot of, just add this import in `app.js`:

``` js
import React from 'preact-compat';
```

**Comment by anaibol** [comment]
I am not defining any JSX Pragma. That fix worked :)
I will continue dealing with react-redux.. Thanks!

**Comment by developit** [comment]
That is awesome! Definitely keep me in the loop on your stuff, looking forward to seeing some super fast preact+redux apps :)

**Comment by anaibol** [comment]
Well, I've been trying passing the store as a prop and getting it from the Provider component constructor, but the constructor function does not receives the props as argument. I am looking in the preact code, do you have an idea?

**Comment by developit** [comment]
hey - got a comment but it must have been deleted - passing props through the constructor was added in preact 2.4.0 :)

**Comment by anaibol** [comment]
Yes, I've seen :) but we now have the issue that preact doesn't support contexts. The redux-connect Provider component use that feature of react to pass the props (the store) to the child component.

**Comment by developit** [comment]
Yup, looking into that today for sure. Tracking it in [Issue #7](https://github.com/developit/preact/issues/7).
