### ISSUE TITLE
Webpack 2 compatible?

### ISSUE THREAD

**Issue by katopz** [developit/preact-compat-example#6]
Hi,

I try to compare [webpack2 tree shaking](https://medium.com/modus-create-front-end-development/webpack-2-tree-shaking-configuration-9f1de90f3233#.2rrasdnsz) result with rollup but it seem like it need more than monkey patch.
BTW I also try apply preact to [that example](https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2) , good news is it did compile but bad news is it throw error on browser...

```
Uncaught TypeError: Cannot read property 'isRequired' of undefined
```

Seem like something is missing there.
I think I try everything I can think of (which is not much) and I'm out of luck now.

Any hint?

**Comment by developit** [comment]
Ah, glad someone else is looking at this too. 
Tree shaking should definitely be workable here, just we-ll have to play with the Babel presets, disabling CommonJS module output since Webpack 2 handles that internally. 

As for the other demo, I'll try swapping as well and let you know what I find.

**Comment by developit** [comment]
@katopz I pushed a [webpack-2 branch](https://github.com/developit/preact-compat-example/tree/webpack-2) that shows a "working" webpack 2 + tree-shaking setup, though the output size appears to be basically the same.  This is probably because preact-compat-example is using every single component in `react-toolbox`.

Note that I had to use `npm 3` to get this to work, since webpack 2 is not yet officially supported as a peer dependency of many webpack plugins.

**Comment by katopz** [comment]
@developit Thanks! You're my hero! :santa: 

BTW, I got some question, refer to babel

``` json
{
  "presets": ["es2015", "stage-0", "react"]
}
```

you don't need to use `"es2015-native-modules"` ([refer to this](https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2/blob/master/.babelrc#L2))? 

Just curious there, all this is new to me and I think I'll leave it settle for a while cause I had fun enough. 

Anyway I did use rollup for some project before. The question is webpack seem to be more legit after Three-Shaking support. So which one you pick or plan on this bundler war?

Cheers!

**Comment by developit** [comment]
Hiya - it actually is using `"es2015-native-modules"`, just not in the babelrc. The babelrc gets used for a bunch of things that would still want commonjs output, such as `webpack.config.babel.js`.  So I have the webpack configuration actually override `presets` to replace `es2015*` with the native modules one ([here](https://github.com/developit/preact-compat-example/blob/webpack-2/webpack.config.babel.js#L46-L50)).

As for rollup VS webpack - I still end up using webpack for apps, because I rely on a bunch of loaders for LESS and those types of things (very much webpack-specific).  However, for libraries I have moved pretty much everything to Rollup since it produces much cleaner and smaller output.

Cheers!
