### ISSUE TITLE
14.3kb (gzipped) including everything? (preact-compact, react-toolbox, all components, css, ...)  

### ISSUE THREAD

**Issue by mehdi-cit** [developit/preact-compat-example#9]
Well All is is in the question.
is there a way to get an even smaller overall size if one only uses a subset of components (I.e. only necessary js and css are to be included).
Thank you much for the libraries you provide!

**Comment by developit** [comment]
Hi @mehdi-cit!  This is actually already the case!  This demo is 14.3kb because it actually uses all of the components. Nothing can be pruned out or subsetted, because all of the components are being shown in the demo (as a way to show that `preact-compat` supports all of the components).

In your own application, as long as you use [the recommended import style](https://github.com/developit/preact-compat-example/blob/master/src/components/dialog-example/index.js#L2-L3), you will only be bundling the components and CSS you actually use.

I'm going to close this issue out since I think that was what you were getting at, but please feel free to ask more questions or correct me if I misinterpreted you! 😊

**Comment by mehdi-cit** [comment]
Great! that was it, I wanted to make sure I got it right. I am trying to use/test preact with purecss for minimizing the overall app size, but it'd be much more elguant to use preact together with preact-compat and the toolbox!
Thank you again for a great job!

**Comment by developit** [comment]
Both are great approaches, just quite different. If you're trying to keep things as light as possible, using Preact without preact-compat will save you around 3kb.  PureCSS is super tiny too, so its a nice fit for a preact app.
